### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Yahenda** [lgarron/chrome-devices-in-new-tab#3]
Hello - while this is an excellent and very functional extension... now that Google Chrome and even the Google search page itself come with Dark Mode, this extension sticks out harshly and genuinely reduces the quality of the experience using it. Please consider providing a dark mode option or at least allowing it to be modified by other dark mode theming extensions (such as "Dark Reader", which is what I currently use). Currently, the desire to look into other options to achieve both dark mode and "chrome-devices-in-new-tab" functionality is only growing.

Thanks very much.

**Comment by lgarron** [comment]
Thanks for the request!

I've wanted to do this for a while, but I didn't find a good way to pick colors. Do you know of a similar kind of table view that has a nice dark color scheme?

**Comment by Yahenda** [comment]
Hi,

First, it’s great to get a quick response from a developer, so thanks very much for that… Now, I’ve been troubleshooting the issue just now and I found that when Chrome’s native Dark Mode is turned on, you can view tabs from other synced devices simply by going to Chrome’s History (Command - Y) and clicking in the top left link: “Tabs from other devices”. If you’re looking for a congruent feel, you couldn’t do much better than Chrome’s own colour scheme, so I suppose that would be the best starting point.

You can also use the direct link: chrome://history/syncedTabs <chrome://history/syncedTabs>

Thanks very much for your efforts!

Sincerely,

Sergio
